[pytest]
log_cli = true
addopts = -s --env=dev --alluredir=./allure-results --clean-alluredir
testpaths = tests
markers =
    smoke: smoke/regression gateway cases
    pim: employee management module cases
